#define PIDLG 1  	/* TREE */
#define PRGNAME 6  	/* OBJECT in TREE #1 */
#define PRGFILE 1  	/* OBJECT in TREE #1 */
#define RESPOND2 8  	/* OBJECT in TREE #1 */
#define PRGGEM 3  	/* OBJECT in TREE #1 */
#define PRGTOS 4  	/* OBJECT in TREE #1 */
#define ABOUTDLG 4  	/* TREE */
#define PIOK 9  	/* OBJECT in TREE #1 */
#define BIDLG 2  	/* TREE */
#define BNAME 1  	/* OBJECT in TREE #2 */
#define BOK 3  	/* OBJECT in TREE #2 */
#define PRGGTP 10  	/* OBJECT in TREE #1 */
#define PRGTTP 11  	/* OBJECT in TREE #1 */
#define PICANCEL 12  	/* OBJECT in TREE #1 */
#define BCANCEL 4  	/* OBJECT in TREE #2 */
#define CMDDLG 3  	/* TREE */
#define CMDOK 4  	/* OBJECT in TREE #3 */
#define CMDNO 3  	/* OBJECT in TREE #3 */
#define CMDINF 2  	/* OBJECT in TREE #3 */
#define ZAPTEXT 5  	/* OBJECT in TREE #2 */
#define ABINFO 6  	/* OBJECT in TREE #4 */
#define ABOK 7  	/* OBJECT in TREE #4 */
#define MOREDLG 5  	/* TREE */
#define MOK 11  	/* OBJECT in TREE #5 */
#define MENU 0  	/* TREE */
#define ADDL 40  	/* OBJECT in TREE #0 */
#define REMOVEL 41  	/* OBJECT in TREE #0 */
#define FSL 43  	/* OBJECT in TREE #0 */
#define SAVEL 44  	/* OBJECT in TREE #0 */
#define ABOUTL 38  	/* OBJECT in TREE #0 */
#define SAVEASL 45  	/* OBJECT in TREE #0 */
#define EXECUTEL 47  	/* OBJECT in TREE #0 */
#define EXITL 48  	/* OBJECT in TREE #0 */
#define PIL 42  	/* OBJECT in TREE #0 */
#define NEWMH 46  	/* OBJECT in TREE #0 */
