#define MENU 0  	/* TREE */
#define DRIVES 1  	/* TREE */
#define A 2  	/* OBJECT in TREE #1 */
#define B 4  	/* OBJECT in TREE #1 */
#define C 6  	/* OBJECT in TREE #1 */
#define D 8  	/* OBJECT in TREE #1 */
#define E 10  	/* OBJECT in TREE #1 */
#define F 12  	/* OBJECT in TREE #1 */
#define G 13  	/* OBJECT in TREE #1 */
#define H 14  	/* OBJECT in TREE #1 */
#define I 15  	/* OBJECT in TREE #1 */
#define J 16  	/* OBJECT in TREE #1 */
#define K 17  	/* OBJECT in TREE #1 */
#define L 18  	/* OBJECT in TREE #1 */
#define M 19  	/* OBJECT in TREE #1 */
#define N 3  	/* OBJECT in TREE #1 */
#define O 5  	/* OBJECT in TREE #1 */
#define P 7  	/* OBJECT in TREE #1 */
#define Q 9  	/* OBJECT in TREE #1 */
#define R 11  	/* OBJECT in TREE #1 */
#define S 20  	/* OBJECT in TREE #1 */
#define T 21  	/* OBJECT in TREE #1 */
#define U 22  	/* OBJECT in TREE #1 */
#define V 23  	/* OBJECT in TREE #1 */
#define W 24  	/* OBJECT in TREE #1 */
#define X 25  	/* OBJECT in TREE #1 */
#define Y 26  	/* OBJECT in TREE #1 */
#define Z 27  	/* OBJECT in TREE #1 */
